name = "flarebase"
compatibility_date = "2025-01-28"
main = "src/index.ts"
workers_dev = true

[vars]
JWT_SECRET = "change_this_in_production"

[[d1_databases]]
binding = "flarebase"
database_name = "flarebase"
database_id = "4979ad43-039b-4b40-8da7-57f847eaef5f"

[[kv_namespaces]]
binding = "flarebase_KV"
id = "21018c1b5938484e84ad8109fbd93820"

# R2 bucket - uncomment after enabling R2 in Cloudflare Dashboard
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "flarebase-files"
# preview_bucket_name = "flarebase-files-dev"

[[durable_objects.bindings]]
name = "flarebase_REALTIME"
class_name = "RealtimeSubscription"

[[durable_objects.bindings]]
name = "flarebase_PRESENCE"
class_name = "UserPresence"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeSubscription", "UserPresence"]